(ns problems.problem2)
(def n1)
(def n2)
(def evenvalues)
(defn solution
  "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with           
   1 and 2, the first 10 terms will be:
     -- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the 
   sum of the even-valued terms."
  [n]
  (binding [n1 1
            n2 2
            evenvalues 2]
    (while (< n2 (+ n))
      ;(println "n1: " n1 " n2: " n2)
      (let [temp (+ n2 n1)]
        (set! n1 n2)
        (set! n2 temp)
        (if (= (mod temp 2) 0)
          (set! evenvalues (+ evenvalues temp)))))
          
    (println "Sum of even values: " evenvalues)
    ))